### ISSUE TITLE
Fails to parse directives with no arguments

### ISSUE THREAD

**Issue by Dig-Doug** [microsoft/cppgraphqlgen#100]
Fails to parse this:

```
directive @id on FIELD_DEFINITION
```

I get an error:

```
Invalid GraphQL: Expected https://facebook.github.io/graphql/June2018/#DirectiveDefinition
	line: 1 column: 14
```

Relevant GraphQL Spec: http://spec.graphql.org/June2018/#example-060af

**Comment by wravery** [comment]
It's not accepting an empty argument list for directive definitions.
