### ISSUE TITLE
boost program_options linking error when compiling schemagen on ubuntu 16.04 with clang++ 9

### ISSUE THREAD

**Issue by svandex** [microsoft/cppgraphqlgen#108]
I have a server with Ubuntu 16.04 and without internet, so I have to copy llvm9.0 prebuilt binary into server.

clang++ with arguments -stdlib=libc++ -fuse-ld=lld

I can build graphqlpeg and graphqlresponse, but with schemagen, I get error with boost::program_options linking error.

```
[  4%] Built target graphqlpeg
[  8%] Built target graphqlresponse
[ 11%] Linking CXX executable schemagen
ld.lld: error: undefined symbol: boost::program_options::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::program_options::options_description const&)
>>> referenced by SchemaGenerator.cpp
>>>               CMakeFiles/schemagen.dir/SchemaGenerator.cpp.o:(outputUsage(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::program_options::options_description const&))

ld.lld: error: undefined symbol: boost::program_options::options_description::options_description(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, unsigned int)
>>> referenced by SchemaGenerator.cpp
>>>               CMakeFiles/schemagen.dir/SchemaGenerator.cpp.o:(main)
>>> referenced by SchemaGenerator.cpp
>>>               CMakeFiles/schemagen.dir/SchemaGenerator.cpp.o:(main)

```
I have tried the newest release 1.73 and the version you have mentioned in README aka 1.65, all failed with the same error.

can you replace boost with other library?

**Comment by svandex** [comment]
I also link .so files manually, it also failed. In my server , there is only one compiler, so boost and cppgraphqlgen use the same compiler.

**Comment by svandex** [comment]
boost compile command
```
./b2 --prefix=/home/appuser/build/boost --with-filesystem --with-program_options variant=debug link=shared threading=multi runtime-link=shared install
```

I also tried to compile static libboost_program_options.a file, it failed too.

**Comment by svandex** [comment]
src/CMakeFiles/schemagen.dir/link.txt

```
/home/appuser/llvm/bin/clang++   -stdlib=libc++   -fuse-ld=lld CMakeFiles/schemagen.dir/SchemaGenerator.cpp.o  -o schemagen  -Wl,-rpath,/home/appuser/build/cppgraphqlgen/src:/home/appuser/boost_1_73_0/stage/lib: libgraphqlpeg.so libgraphqlresponse.so /home/appuser/boost_1_73_0/stage/lib/libboost_program_options.so.1.73.0 /home/appuser/boost_1_73_0/stage/lib/libboost_filesystem.so.1.73.0
```

**Comment by wravery** [comment]
I think the problem is that Boost is using gcc/libstdc++, which is [not compatible](https://stackoverflow.com/questions/8454329/why-cant-clang-with-libc-in-c0x-mode-link-this-boostprogram-options-examp) with clang/libc++. You may need to recompile Boost with clang as well.

**Comment by wravery** [comment]
Ah, I see you mentioned there's only one compiler on the system. This still seems like it might be a standard library mismatch though.

**Comment by wravery** [comment]
Also, make sure it's using C++17 flags when compiling both Boost and cppgraphqlgen.

**Comment by wravery** [comment]
Closing for now since I haven't heard back, if you are still having this problem feel free to re-open the issue.
