### ISSUE TITLE
Float arguments reject whole numbers

### ISSUE THREAD

**Issue by gakio12** [microsoft/cppgraphqlgen#120]
When passing a whole number as an argument that is defined as a Float, the error "not a float" is thrown. For example, the following query fails with "not a float":

```graphql
type Mutation {
    setFloat(float: Float!): Float
}
```
```graphql
mutation a {
  setFloat(float: 0)
}
```
I can resolve this in the generated `resolveSetFloat()` by trying to `require` it as a `response::IntType`, catching a schema_exception, then trying to `require` it as a `response::FloatType`:
```c++
        graphql::response::FloatType argFloat;
	
	try {
		argFloat = service::ModifiedArgument<response::IntType>::require("float", params.arguments);
	} catch (graphql::service::schema_exception & ex) {
		argFloat = service::ModifiedArgument<response::FloatType>::require("float", params.arguments);
	}
```
I think this can be fixed in the library `GraphQLService.cpp` by changing this:
```c++
template <>
response::FloatType ModifiedArgument<response::FloatType>::convert(const response::Value& value)
{
	if (value.type() != response::Type::Float)
	{
		throw schema_exception { { "not a float" } };
	}

	return value.get<response::FloatType>();
}
```
to
```c++
template <>
response::FloatType ModifiedArgument<response::FloatType>::convert(const response::Value& value)
{
	if (value.type() != response::Type::Float || value.type() != response::Type::Int)
	{
		throw schema_exception { { "not a float" } };
	}

	return value.get<response::FloatType>();
}
```

Thoughts? I can create a pull request for this later, but I wanted to get this out there.

vcpkg version: 2020.02.04
cppgraphqlgen version: 3.2.2
OS: Debian Buster

**Comment by gakio12** [comment]
As a follow-on, and maybe this should be a new issue, but changing the `float` argument to `0.1` results in the following error.
```
GraphQL:2:14: Expected )
```

**Comment by wravery** [comment]
The followup is definitely a bug, I think it's caused by the order of the types it matches in GraphQLGrammar.h for `input_value_content`.

But I think rejecting whole numbers is correct. The spec says that [FloatValue](http://spec.graphql.org/June2018/#sec-Float-Value) must always include a Fractional Part, an Exponent Part, or both.

**Comment by gakio12** [comment]
The GraphQL spec defines input coercion for Float as accepting an int value or float value.

http://spec.graphql.org/June2018/#sec-Float

**Comment by wravery** [comment]
Ah, you're correct. I think that's the only type that has this bug, it looks like the other built-in types all have stricter input coercion.

**Comment by wravery** [comment]
@gakio12, thanks for the bug report, and thanks for the offer to do a PR as well. I happened to already have the project open and I was just adding tests with those mock objects already. So it was easier to reproduce the bugs with the tests and fix them at the same time.
