### ISSUE TITLE
Changing MapData to a simple std::map?

### ISSUE THREAD

**Issue by barbieri** [microsoft/cppgraphqlgen#130]
Currently the MapData uses an unordered map and a vector, this is likely used to keep the insertion order, however there is no requirement the results should be in a specific order (at least changing this breaks the tests, that expects the JSON serialization to be equal, instead of comparing the objects).

However this is resulting in 2 strings to be created, plus the extra indirections to get the pairs.

Could we change the MapData to be a std::map and fix the tests?

**Comment by wravery** [comment]
The spec actually contradicts this: http://spec.graphql.org/June2018/#sec-Serialized-Map-Ordering.

**Comment by barbieri** [comment]
ok, it's a SHOULD not a MUST, but I get your point.

I think after we tackle #127 and with my #126 PR we basically stop searching the maps (or at least we could), then eventually we may drop the `unordered_map` part of it (or at least make it a compile option, that I could disable in order to save CPU/memory).
