### ISSUE TITLE
improve static data structures

### ISSUE THREAD

**Issue by barbieri** [microsoft/cppgraphqlgen#139]
Some static data structures, such as resolver map and the validation information could use some better data structures, in particular avoiding runtime computation, trading it for compile-time whenever possible.

https://blog.quarkslab.com/frozen-an-header-only-constexpr-alternative-to-gperf-for-c14-users.html

could be interesting to this project and the generated code.

**Comment by wravery** [comment]
I realized that the `internal::sorted_map` and `internal::sorted_set` should already be convertible to `constexpr` in C++20. The new standard enabled `constexpr` versions of `std::less`, `std::sort`, `std::vector`, and `std::equal_range`. All it should take is declaring the `internal::shorter_or_less` comparator `constexpr` and declaring the constructors and other methods on these types as `constexpr` as well.
