### ISSUE TITLE
Enum arguments not marked as maybe_enum

### ISSUE THREAD

**Issue by gitmodimo** [microsoft/cppgraphqlgen#178]
When enum is passed as argument` ModifiedArgument<MX::MyEnumType>::convert(const response::Value& value)` throws `service::schema_exception { { "not a valid MyEnumType value" } };` because `value.maybe_enum()` is not satisfied.
For now I commented out this check, but it seems like it should be marked as enum in parser.

**Comment by wravery** [comment]
Take a look at: https://github.com/microsoft/cppgraphqlgen/blob/615f800020f2ec9039987a0d5cb2ff93e46784d9/include/graphqlservice/GraphQLResponse.h#L144

The parser uses this to flag string values as potential enum values when they come from JSON, and when you programmatically instantiate a `response::Value` with an enum you should do the same.

**Comment by wravery** [comment]
Better yet, initialize it as an EnumValue explicitly, like ModifiedResult: https://github.com/microsoft/cppgraphqlgen/blob/615f800020f2ec9039987a0d5cb2ff93e46784d9/samples/separate/TodaySchema.cpp#L55

**Comment by gitmodimo** [comment]
Ooooh. Somehow it slipped my mind that arguments are not in fact part of the graphql query. Thanks
