### ISSUE TITLE
Getting only the selected GraphQL fields to DB query

### ISSUE THREAD

**Issue by paussu** [microsoft/cppgraphqlgen#182]
Hi,

We have been using this library successfully by getting all the fields from our database and then the service gets the fields that were requested. Now we are researching the possibility to filter out those fields from the database query also.

Any ideas on how we could get the fields from the request to the DB query? The DB queries are currently handled in our query resolvers.

Thanks!

**Comment by wravery** [comment]
This should make it transparent to your callers. It'll defer the DB query until all of the field accessors have been called, and defer the actual results from those fields until after the DB query has been issued:

- Override `beginSelectionSet` and `endSelectionSet`.
- In `beginSelectionSet`, start recording calls to the field accessors on your object, building the set of columns you're going to request from the DB either in your object using `mutable`/`const_cast`, or by putting it in the optional `RequestState`.
- Each field accessor should return a `std::future` from a `std::promise`, which you record along with the column in the pending DB query.
- Once you get the `endSelectionSet` call, issue the DB query and fulfill the pending `std::promise` for each field that was requested since `beginSelectionSet` with the results.

That's the theory behind `Object::beginSelectionSet` and `Object::endSelectionSet`. I've never actually implemented that pattern myself, so if it works for you, I'd love to hear about it.

**Comment by paussu** [comment]
Interesting. I was wondering if those function could be of use.

Now if I understood correctly we should record the field accessors on the objects we are returning with the query.
But how those field accessors are accessed if no objects are there yet?

Just to give some idea, our code is currently going in this order:
1.     object::Query::resolveGetItems()
2.     Query::getItems() - this does the DB query and returns ItemObjects
3.     ItemObject::resolve()
4.     Item::resolveName()
5.     Item::getName() - here's the column name

**Comment by wravery** [comment]
Yeah, nested objects can't really be batched this way, you'd need at least 2 DB queries, unless you already know at least how many items there are. If you are using paged queries, you might be able to use the page size for the count. I'm not sure this will work, but to batch queries across an object hierarchy, I'd try:

1. Get the set of itemIds (or at least the item count) and create empty `ItemObject` placeholders in the `Query::getItems()` call.
2. Return the placeholder objects from `Query::getItems`, it should start evaluating the selection set on each item.
3. Start accumulating the set of fields you need for each `ItemObject` (should be the same for all of them, but maybe not if you are using interfaces or unions with different fragment spreads) using the `beginSelectionSet`/`endSelectionSet` per `Item`. Each `Item` should store its set of fields and pending promises in `Query` with an identifier or index so when `Query` gets the results back, it can fill them in.
4. Wait for `Query::endSelectionSet` to issue the DB request. Fill in all the fields that were requested, with whatever `WHERE` clause/filter determined the set of items. When you get the results, fill in the pending `ItemObject` instances with individual results and make each of them fulfill their pending promises.

It's possible `Query::endSelectionSet` will be blocked waiting for the future on each item, which would be blocked on the futures of each field in the items, so this might hit a deadlock. If that happens, and you keep track of how many items have been visited, you could wait until the last `Item::endSelectionSet` call and issue the DB query from there. I don't think it will block on any of the item futures until all of the items in the list have been visited and produced their futures, calling `Item::endSelectionSet` on each of them.

I think this approach only works for a single nested level of objects. Beyond that, I think you probably need to start including a custom `@directive` or argument on the `items` field to tell it which fields you're going to need. I used an approach kind of like this to handle tabular data in https://github.com/microsoft/gqlmapi, which has extensible custom properties that can't be declared in the schema.

**Comment by paussu** [comment]
I've been testing this placeholder method, but it seems I am doing something wrong.

The `Query::endSelectionSet` is called before the `ItemObject` resolving so I tried issuing the DB query in the last `Item::endSelectionSet`, but the code gets stuck waiting for the futures of the first object. 
Specifically in the `ModifiedResult<Object>::convert` function where it gets the wrappedResult.

Currently I'm storing the promises in the `Item` and the field accessors return `get_future` from the according promise. Values are set after the DB query.

But yeah, we could also try the directives approach too. There is also the possibility to use the query AST, but I'm not sure how good idea that is.

Also nice to see this library used in other projects 👍
