### ISSUE TITLE
Subscription thread safety

### ISSUE THREAD

**Issue by gitmodimo** [microsoft/cppgraphqlgen#200]
It seems subscribe/unsubscribe/deliver is not thread safe. 
These fields in Request class are not protected:
```
	internal::sorted_map<SubscriptionKey, std::shared_ptr<SubscriptionData>> _subscriptions;
	internal::sorted_map<SubscriptionName, internal::sorted_set<SubscriptionKey>> _listeners;
```

**Comment by Coder666** [comment]
We had the same issue and just put a thread safe wrapper around the desired functionality.  

Note also that running multiple concurrent queries on the service::Request/Operations object is not thread safe either, we simply allocate one per thread/query as required.

**Comment by wravery** [comment]
> We had the same issue and just put a thread safe wrapper around the desired functionality.

This sounds like a good workaround, but I will look into protecting the subscription members.

> Note also that running multiple concurrent queries on the service::Request/Operations object is not thread safe either, we simply allocate one per thread/query as required.

@Coder666, do you mean because of the state in the `ValidateExecutableVisitor` in the `_validation` member? That could be protected too.

**Comment by Coder666** [comment]
Is there any chance of getting this back ported into 3.X.X ?

**Comment by Coder666** [comment]
Cheers
