### ISSUE TITLE
Another client code generation issue in 3.7.0

### ISSUE THREAD

**Issue by Coder666** [microsoft/cppgraphqlgen#201]
Hi,

I have another issue with client code generation, whereby the result returned from a query always has "data" which then contains the query result

The following code is generated to parse the query result:

```
Response parseResponse(response::Value&& response)
{
	Response result;

	if (response.type() == response::Type::Map)
	{
		auto members = response.release<response::MapType>();

		for (auto& member : members)
		{
			if (member.first == R"js(FooBar)js"sv)
			{
				result.eventSecurityCheckFailure = ModifiedResponse<Response::fooBar_FooBar>::parse(std::move(member.second));
				continue;
			}
		}
	}

	return result;
}
```

However this doesn't work with a direct result from a query because the first item is not "FooBar" but "data" for example:

```
    { "data" : { "FooBar" : { ... } } }
```

Obviously I can work around this by extracting the contents from "data" and passing that into the parseResponse function.  Is this indended behaviour or a bug? (it would be nice if it just handled the whole query result)

**Comment by wravery** [comment]
Check out `parseServiceResponse` in `GraphQLClient.h`. The idea is that you would split the full response into a `ServiceResponse` struct with any errors, then use the generated `parseResponse` to parse out just the `data` member.
