### ISSUE TITLE
Is there any interest in contributions to make the clientgen outputs C++17 compatible

### ISSUE THREAD

**Issue by ALTinners** [microsoft/cppgraphqlgen#217]
I've been using this lib (which is great by the way :D ) to generate a server for a standalone project, and a little helper lib for a client program we intend to plug into it. 

This client program is unfortunately restricted to ++17 due to another 3rd party lib which uses language features that were removed in 20. 

I've had a play around with modifying the CMakeLists and have ended up with both a ++20 aware server compiling, as well as a test program using the `clientgen` outputs that is only ++17 aware. 

Obviously having ++17 compatible `clientgen` code should improve the distributability of client code - but might put it at odds with the expected roadmap (or just make it harder to maintain). 

Curious to see if that would be welcome addition or not - let me know.

**Comment by wravery** [comment]
I don't want to guarantee that `clientgen` or one of the runtime libraries the generated code links to won't eventually require C++20 (or later) in the future, but if/when there's a change that big, it'll probably trigger a 5.x version. I think it's safe to pursue this for the 4.x series. 👍🏼
