### ISSUE TITLE
Is there a reason clientgen only outputs one operation if there are multiple in a .graphql file?

### ISSUE THREAD

**Issue by ALTinners** [microsoft/cppgraphqlgen#218]
I have a `.graphql` file that looks like this 

```
fragment ginormousSubsetOfCommonData on MainDataObj {
   # insert 30 line monster here
}

subscription MainDataObjA { 
   aSub {
      ...ginormousSubsetOfCommonData
   }
}

subscription MainDataObjB { 
   bSub {
      ...ginormousSubsetOfCommonData
   }
}

# repeated many times in a very boilerplatey fashion

subscription MainDataObjZ { 
   zSub {
      ...ginormousSubsetOfCommonData
   }
}

```

Where all the `MainDataObj#` are implementations of `MainDataObj` 

When doing the equivalent work for a client side element (iOS, using Apollo's GraphQL tools) they had all the outputs from the `clientgen` equivalent in a single file - which made managing it a bit easier. 

Is there a reason that `clientgen` only outputs one op from a file? Would that be amenable to change to support usecases which use big piles of fragments to save either `.graphql` repetition or `cmake` repetition?

**Comment by wravery** [comment]
The main reason it uses separate files is that I came around to the opinion that `schemagen` worked better in `--separate-files` mode and it should be the default. However, I definitely see how `clientgen` could be improved. It could still create separate files for each operation, but by default (or with another option for the one allowed unnamed operation) it could use the name of the operation and output everything that way. Like `schemagen`, the CMake helpers could automate a lot of the multi-file handling.

**Comment by wravery** [comment]
Actually, in a multi-operation request document, every request would have the same AST. I think maybe they should be in the same file, but each request should also have an accessor to get the name of the operation, so the caller doesn't need to hardcode a matching string literal.
