### ISSUE TITLE
Including headers from the right path in autogenerated files

### ISSUE THREAD

**Issue by paussu** [microsoft/cppgraphqlgen#226]
Hi,

We have stumbled upon another issue in the upgrade. 

We are using multiple separate schemas in our project and there seems to some problems with includes for objects that have same name. For example `schema1/QueryObject.h` and `schema2/QueryObject.h`. 
Both `QueryObject.cpp` are including `#include "QueryObject.h"`, but other one is getting the wrong one.

Our current version maybe works because of the `SchemaObjects.h` includes in every object .cpp file?

Could we have an option to add a folder name to the including of autogenerated headers? Or is there some other way we can handle this kind of situation?

Thanks again.

**Comment by wravery** [comment]
If I'm understanding the project structure, I think you can probably set the include path separately for each schema. It sounds like every schema include directory is being searched for every other schema, which implies that they are all being added to the include path at once, perhaps in an inherited CMake target.

**Comment by paussu** [comment]
Well we are currently using Visual Studio projects (changing it for CMake is in the plans though).

Maybe the problem is that all the schemas are in the same project / module and we should separate them? Currently the schemas are separated to their own folders but they are all included in the same project.

**Comment by wravery** [comment]
That makes sense, I think using separate projects and then linking them into a shared project later should work.

**Comment by paussu** [comment]
Okay, I think that is the way to go with this.

Thanks for your guidance 👍
