### ISSUE TITLE
Is json supported as an input request?

### ISSUE THREAD

**Issue by TrevorMellon** [microsoft/cppgraphqlgen#238]
I may be missing something but I can't seem to get this library to parse json input, only output.

Must node and python libraries send 'application/json', what do I need to do to handle that?

**Comment by TrevorMellon** [comment]
I figured out how to do it manually, but still unsure how to get variables to work, an example would help

**Comment by wravery** [comment]
Yes 👍🏼 , take a look at `parseJSON` in [graphqlservice/JSONResponse.h](https://github.com/microsoft/cppgraphqlgen/blob/main/include/graphqlservice/JSONResponse.h).
