### ISSUE TITLE
Issues reported by SonarQube in autogenerated files

### ISSUE THREAD

**Issue by paussu** [microsoft/cppgraphqlgen#272]
I thought it might be better I report the SonarQube issues and you can decide their validity and what to do about them.

These are not that severe, but since they are in the autogenerated files they do come up quite often in pull requests.

### Schema header:
![kuva](https://user-images.githubusercontent.com/27086922/189067104-90090c00-663f-4851-9b23-0bf7056d9982.png)

### Object header
![kuva](https://user-images.githubusercontent.com/27086922/189055282-aacc2aea-cb57-45e2-a48e-e347114b5e1e.png)

Why replace the final with override:
The class is already final, so no need to declare the functions as final:

![kuva](https://user-images.githubusercontent.com/27086922/189057372-d57b2904-d6a3-400c-9732-47037a9877e6.png)

### Schema source
![kuva](https://user-images.githubusercontent.com/27086922/189068343-c5a1d085-9302-46d0-a3a8-edd31b686f19.png)

![kuva](https://user-images.githubusercontent.com/27086922/189068984-71366603-f9a7-4d07-95be-ad753932ec5d.png)

### Object source
The bug one I already mentioned earlier. It is also saying that the result is unused, not sure why, might be a false positive.

![kuva](https://user-images.githubusercontent.com/27086922/189054932-db98fc98-aa63-418b-9fde-8193be20be1f.png)

**Comment by wravery** [comment]
I think I fixed all of these, except for that last one that looked like a false positive.

**Comment by paussu** [comment]
Very nice update, thanks 🙂
