### ISSUE TITLE
Access Violation when using optional input values

### ISSUE THREAD

**Issue by JamesPeters98** [microsoft/cppgraphqlgen#277]
I appear to be running into an access violation when trying to serialize an input object with optional values.

When calling nullableValue.reset() I get the access violation:
https://github.com/microsoft/cppgraphqlgen/blame/main/include/graphqlservice/GraphQLClient.h#L167

![image](https://user-images.githubusercontent.com/2249693/212371091-f7e1610b-8a6c-4985-b89f-cdbf8a4b49ef.png)

**Comment by JamesPeters98** [comment]
I think something else might be causing this actually.

**Comment by JamesPeters98** [comment]
All ModifiedVariable's appear to have the same problem for me, optional or not:

![image](https://user-images.githubusercontent.com/2249693/212373732-6e77204b-bcb5-4a1a-b5b6-2f0744283130.png)

**Comment by wravery** [comment]
Glad you solved it, thanks!
