### ISSUE TITLE
Enum Client Gen parsing incorrectly

### ISSUE THREAD

**Issue by JamesPeters98** [microsoft/cppgraphqlgen#278]
Just doing some tests with the client gen and I've noticed that the Enum parsing doesn't appear to be working for me.

This was the generated code:

```
static const std::array<std::pair<std::string_view, NonConformanceReasonType>, 4> s_valuesNonConformanceReasonType = {
	std::make_pair(R"gql(NONE)gql"sv, NonConformanceReasonType::NONE),
	std::make_pair(R"gql(REDELIVERY)gql"sv, NonConformanceReasonType::REDELIVERY),
	std::make_pair(R"gql(RETURN)gql"sv, NonConformanceReasonType::RETURN),
	std::make_pair(R"gql(SHORT)gql"sv, NonConformanceReasonType::SHORT)
};

template <>
NonConformanceReasonType Response<NonConformanceReasonType>::parse(response::Value&& value)
{
	if (!value.maybe_enum())
	{
		throw std::logic_error { R"ex(not a valid NonConformanceReasonType value)ex" };
	}

	const auto result = internal::sorted_map_lookup<internal::shorter_or_less>(
		s_valuesNonConformanceReasonType,
		std::string_view { value.get<std::string>() });

	if (!result)
	{
		throw std::logic_error { R"ex(not a valid NonConformanceReasonType value)ex" };
	}

	return *result;
}
```

Here's what the parsing function returns for each enum string whilst debugging:

![image](https://user-images.githubusercontent.com/2249693/213760943-4a1ef1ef-f972-496f-9bf6-8550e7179923.png)

I think this has something to do with the shorter_or_less sort?

**Comment by wravery** [comment]
Yes, you're correct. It looks like `clientgen` emitted them in the wrong order when it defined `s_valuesNonConformanceReasonType`. It should have been pre-sorted as `NONE`, `SHORT`, `RETURN`, `REDELIVERY`.

**Comment by wravery** [comment]
I think this is the same as #265.

**Comment by wravery** [comment]
Yup, just need to publish another release with the fixes since then (and probably update `vcpkg` as well). If you are building `cppgraphqlgen` yourself, you can get the fix already by pulling from `main`.

**Comment by JamesPeters98** [comment]
Okay thanks! When will 4.5.1 be available in vcpkg?

**Comment by wravery** [comment]
As soon as https://github.com/microsoft/vcpkg/pull/29086 is merged. :)
