### ISSUE TITLE
Parsing "integer" double causes "GraphQL only supports 32-bit signed integers" error

### ISSUE THREAD

**Issue by gitmodimo** [microsoft/cppgraphqlgen#295]
When js number is converted to JSON using JSON.stringify we cannot control output format. Big number intended to be floating point can resemble integer number. This triggers "GraphQL only supports 32-bit signed integers" in JSONResponse.cpp.
We probably should guess that integers bigger than int32 are in fact double?

```
	bool Uint(unsigned int i)
	{
		if (i > static_cast<unsigned int>(std::numeric_limits<int>::max()))
		{
			return Double(static_cast<double>(i));
		}
		return Int(static_cast<int>(i));
	}

	bool Int64(int64_t i)
	{
		return Double(static_cast<double>(i));
	}

	bool Uint64(uint64_t i)
	{
		return Double(static_cast<double>(i));
	}


```

**Comment by wravery** [comment]
If you want to handle C++ `double` values, I think you need to use the GraphQL [Float](https://spec.graphql.org/October2021/#sec-Float) scalar type in your schema.

**Comment by gitmodimo** [comment]
Yes rapidjson does not know anything about schemat and desired types.
In my case I have defined input type that contains Float. When json serializes big float value it write out 1000000000 instead od 1e9 in JS. Rapidjson treats this value as uint64_t and graphql parser discards it as out of range integer.  Even though we wanted a float.

**Comment by wravery** [comment]
got it, makes sense
