### ISSUE TITLE
PEGTL backtracking on field_arguments

### ISSUE THREAD

**Issue by gruzdev** [microsoft/cppgraphqlgen#302]
The **field_content** rule in Grammar.h is formulated in terms or **sor**. It introduces a lot of backtracking on **field_arguments**. Why not just make **field_selection_set** optional? Am I missing something?
`struct field_content
	: seq<field_arguments, opt<field_directives>, opt<field_selection_set>>
{
};`

**Comment by wravery** [comment]
Makes sense, I don't see any reason not to make this change. Thanks for the suggestion!
