### ISSUE TITLE
libgraphqlpeg can't parse float with fractional and exponential parts

### ISSUE THREAD

**Issue by gruzdev** [microsoft/cppgraphqlgen#306]
My test case:
```
TEST(PegtlExecutableCase, ParseFloatWithFractionalAndExponentialParts)
{
	memory_input<> input(R"gql(
		{
		  field(value: 1.1e1)
		})gql",
		"ParseFloatWithFractionalAndExponentialParts");

	const bool result = parse<executable_document>(input);

	ASSERT_TRUE(result) << "we should be able to parse the doc";
}
```
The error:
`parse error matching tao::graphqlpeg::ascii::one<')'>" thrown in the test body.`

What helps is using this rule for the **float_value**:
`struct float_value : seq<integer_part, sor<seq<fractional_part, opt<exponent_part>>, exponent_part>>`
But the original rule looks correct . Not sure what is going wrong here.

**Comment by wravery** [comment]
Thanks for the suggestion! I think I understand why the existing rule didn't work and this one did. The grammar rule for `float_value` would not back up and retry the `seq<fractional_part, exponent_part>` once it had successfully matched the first `fractional_part`.
