### ISSUE TITLE
Invalid enum values cause segmentation fault.

### ISSUE THREAD

**Issue by gitmodimo** [microsoft/cppgraphqlgen#334]
When [enum vale is out of range](https://github.com/gitmodimo/cppgraphqlgen/commit/0d066ccab7e5ae1149f42e2f293c1d68a5c661f1) due to being uninitialized of any other reason the library [segfaults](https://github.com/gitmodimo/cppgraphqlgen/actions/runs/11702411503/job/32590537513). 

The [fix](https://github.com/gitmodimo/cppgraphqlgen/commit/51d966ce87d1e90e2b8f3c902b2afdea0801b467) is easy and I think the library should not segfault on bad/uninitialized enum value.

Edit:
Tests after fix fail due to bad results not by segfault.

**Comment by wravery** [comment]
The proposed fix looks good, want to spin up a PR? I don't want to bypass the CLA and such by just integrating it myself, but if the PR targets either `main` or `next` I can make sure it's merged for `v5.0`.

**Comment by gitmodimo** [comment]
PR ready . LMK if you want me to do one for [this](https://github.com/microsoft/cppgraphqlgen/issues/311#issuecomment-2457733249).
