### ISSUE TITLE
cmake fails in ubuntu 18.04

### ISSUE THREAD

**Issue by alkismavridis** [Microsoft/cppgraphqlgen#51]
cmake brings the following error:
```
cmake .
CMake Error at CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "pegtl" with any of
  the following names:

    pegtlConfig.cmake
    pegtl-config.cmake

  Add the installation prefix of "pegtl" to CMAKE_PREFIX_PATH or set
  "pegtl_DIR" to a directory containing one of the above files.  If "pegtl"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/alkis/p/cpp/graphql/cppgraphqlgen/CMakeFiles/CMakeOutput.log".
See also "/home/alkis/p/cpp/graphql/cppgraphqlgen/CMakeFiles/CMakeError.log".
```

I tried to run 
`sudo apt install pegtl-dev`
which installed a bunch of header files under /usr/include/pegtl, but cmake still outputs the same error.

How can I proceed?
Thanks a lot!

**Comment by wravery** [comment]
It looks like the `pegtl-dev` package on Ubuntu is a pretty old version, 1.3.1. I've only tested this with PEGTL [2.7.1](/taocpp/PEGTL/releases/tag/2.7.1) myself, there are almost certainly some incompatibilities there based on the major version number. Either way, it looks like this package didn't include the CMake files it needs to find it with `find_package`, so it won't work with the cppgraphqlgen build.

Typically I clone and bootstrap [vcpkg](/Microsoft/vcpkg) first to install the dependencies for cppgraphqlgen on my Linux systems, then I run CMake for cppgraphqlgen with the `-DCMAKE_TOOLCHAIN_FILE=...` command line option to pull from there. It doesn't even require installing the dependencies globally with `sudo`, which is nice. I also made cppgraphqlgen package for vcpkg, so if you go this route you could just build and install it with the dependencies in one step.

To build it from scratch, you'll need Google Test (available in apt as `googletest`), or you'll need to turn off building the tests in any of these projects if they complain. Clone the `2.x` branch of [PEGTL](/taocpp/PEGTL/tree/2.x) and the master branch of [RapidJSON](/Tencent/rapidjson) locally and then run the following commands from each of those directories:

```
cmake
cmake --build .
sudo cmake -P cmake_install.cmake
```

This should setup the CMake packages where cppgraphqlgen can find them. If you don't have Google Test, you can suppress building tests in cppgraphqlgen with `-DBUILD_TESTS=OFF` on the first `cmake` command. I'm not sure about the other two.
