### ISSUE TITLE
Replace reserved identifiers

### ISSUE THREAD

**Issue by d-frey** [Microsoft/cppgraphqlgen#55]
I noticed that you used reserved identifiers in a few places, namely `_Rule`, `_Input`, `_States`, `_Type` and `_Value`. Those are reserved by the C++ standard (everything that starts with underscore plus an uppercase character). They need to be replaced with something else, and as I don't know what style you'd prefer I'll leave it to you to choose.

**Comment by d-frey** [comment]
I think the issue is resolved now, but the commit comment was not recognized by GitHub, so I'll close it manually. If that is wrong just reopen it.

**Comment by d-frey** [comment]
D'oh, sorry, my mistake.

**Comment by wravery** [comment]
Yup, still pending in my personal fork.
