### ISSUE TITLE
Undefined reference to std::vector<string> in samples

### ISSUE THREAD

**Issue by Bjoe** [microsoft/cppgraphqlgen#63]
Unfortunately I get a undefined reference to std::vector<string> when I compile the samples/tests.

My environment:
Ubuntu 19.04 disco with clang 8.0.1

Verbose linker output:
`clang version 8.0.1-svn360950-1~exp1~20190517001536.70 (branches/release_80)`
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
`"/usr/bin/ld" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o samples/sample /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../.. -L/usr/lib/llvm-8/bin/../lib -L/lib -L/usr/lib samples/CMakeFiles/sample.dir/today/sample.cpp.o samples/libseparategraphql.a src/libgraphqljson.a src/libgraphqlservice.a src/libgraphqlpeg.a -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o`

Link error:
```
/usr/bin/ld: samples/libseparategraphql.a(SeparateToday.cpp.o): in function `graphql::today::EdgeConstraints<graphql::today::Appointment, graphql::today::AppointmentConnection>::operator()(std::optional<int> const&, std::optional<graphql::response::Value> const&, std::optional<int> const&, std::optional<graphql::response::Value> const&) const':
SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x583): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'

```

Full error output:
```
[2/2 0.3/sec] Linking CXX executable samples/sample
FAILED: samples/sample 
: && /usr/bin/clang++  -std=c++17   samples/CMakeFiles/sample.dir/today/sample.cpp.o  -o samples/sample  -v samples/libseparategraphql.a src/libgraphqljson.a src/libgraphqlservice.a src/libgraphqlpeg.a -lpthread && :
clang version 8.0.1-svn360950-1~exp1~20190517001536.70 (branches/release_80)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o samples/sample /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../.. -L/usr/lib/llvm-8/bin/../lib -L/lib -L/usr/lib samples/CMakeFiles/sample.dir/today/sample.cpp.o samples/libseparategraphql.a src/libgraphqljson.a src/libgraphqlservice.a src/libgraphqlpeg.a -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: samples/libseparategraphql.a(SeparateToday.cpp.o): in function `graphql::today::EdgeConstraints<graphql::today::Appointment, graphql::today::AppointmentConnection>::operator()(std::optional<int> const&, std::optional<graphql::response::Value> const&, std::optional<int> const&, std::optional<graphql::response::Value> const&) const':
SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x583): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
/usr/bin/ld: SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_11AppointmentENS0_21AppointmentConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x8b8): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
/usr/bin/ld: samples/libseparategraphql.a(SeparateToday.cpp.o): in function `graphql::today::EdgeConstraints<graphql::today::Task, graphql::today::TaskConnection>::operator()(std::optional<int> const&, std::optional<graphql::response::Value> const&, std::optional<int> const&, std::optional<graphql::response::Value> const&) const':
SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_4TaskENS0_14TaskConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_4TaskENS0_14TaskConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x583): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
/usr/bin/ld: SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_4TaskENS0_14TaskConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_4TaskENS0_14TaskConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x8b8): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
/usr/bin/ld: samples/libseparategraphql.a(SeparateToday.cpp.o): in function `graphql::today::EdgeConstraints<graphql::today::Folder, graphql::today::FolderConnection>::operator()(std::optional<int> const&, std::optional<graphql::response::Value> const&, std::optional<int> const&, std::optional<graphql::response::Value> const&) const':
SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_6FolderENS0_16FolderConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_6FolderENS0_16FolderConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x583): undefined reference to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()'
/usr/bin/ld: samples/libseparategraphql.a(SeparateToday.cpp.o):SeparateToday.cpp:(.text._ZNK7graphql5today15EdgeConstraintsINS0_6FolderENS0_16FolderConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_[_ZNK7graphql5today15EdgeConstraintsINS0_6FolderENS0_16FolderConnectionEEclERKSt8optionalIiERKS5_INS_8response5ValueEES8_SD_]+0x8b8): more undefined references to `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector()' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
08:17:47: The process "/usr/bin/cmake" exited with code 1.
```

Any idea?

**Comment by wravery** [comment]
I ran into a similar issue when I switched from Debug to Release on a Mac with VS Code and the CMake Tools extension. I figured it might have been an issue with the extension because it went away when I switched the configuration back.

From what I can tell in a few web searches, this can happen when you try to use clang with libc++ for the stdlib and you either don't link with `-lc++` and `-lc++abi` or you don't set the `-stdlib=libc++` option. There was also something in the search results about this happening specifically on Ubuntu, I think because of the way the `update-alternatives` command symlinks the `c++` command to different executables.

**Comment by wravery** [comment]
I got the same failure with a Release build and `g++` (with a slightly different symbol for the other stdlib), so I don't think this is related to `clang` and `libc++` anymore. I think something about the way I'm using an `OBJECT` library is including those symbols in Debug but not in Release.

**Comment by wravery** [comment]
Turns out it was the spot where I constructed a service::schema_exception with an implicit temporary value of `std::vector<std::string>` for the argument. I'm using that same syntax everywhere else just fine, including in the unit test executables, but somehow this syntax doesn't pull in the definition of `std::vector<std::string>` by itself. Everywhere else must have been pulling it in some other way.

I think this may be a linker bug, but I found a slightly more explicit syntax (an extra pair of `{ }` around the initializer list) which is not much more verbose. I also made the move and regular constructors for `schema_exception` explicit and deleted the default and copy constructors to try to prevent ambiguous implicit constructor overloading if someone tries to pass a `schema_exception` with type inference.

**Comment by Bjoe** [comment]
For the sake of completeness, your fix works for me as well.
I build the test/samples with clang 8.0.1 with stdc++ and libc++ in Debug and Release.

Btw. I build the samples with stdc++ before ... see [my linker output in my first post](https://github.com/microsoft/cppgraphqlgen/issues/63#issue-479346791): `... -lstdc++ ...`

Thanks for your quick fix!
