### ISSUE TITLE
specialisations of ValueType::get() not obvious in GraphqlResponse.h

### ISSUE THREAD

**Issue by soustelle** [microsoft/cppgraphqlgen#66]
When looking at the definition of ValueType::get() in include/graphqlgen/GraphqlResponse.h,

    91  // Specialized for all Types.
    92  template <typename ValueType>
    93  ValueType get() const;
 
the actually implemented template specialisations are not obvious. For example, trying to access a stringType value by

      v.get<graphql::response::stringType>()

 will result in a linker error:

ctas.cxx:35: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > graphql::response::Value::get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >() const'

This is because the actually implemented specialisation is 

    template <>
    const StringType& Value::get<const StringType&>() const 

Note the const reference type. I think the actually implemented specialisations template specialisation should be listed in GraphqlResponse.h:

- const MapType&    get<const MapType&>()     
-  const ListType&   get<const ListType&>()   
-  const StringType& get<const StringType&>() 
-  const ScalarType& get<const ScalarType&>() 
-  BoleanType        get<BooleanType>() 
-  IntType           get<IntType>()     
-  FloatType         get<FloatType>()

**Comment by wravery** [comment]
At the very least a comment block would help. I'm not sure if I can make it 100% backward-compatible, but introducing a traits template which automatically picks the right type would help too.
