### ISSUE TITLE
Parser refuses valid query input if immediately followed by a fragment definition 

### ISSUE THREAD

**Issue by soustelle** [microsoft/cppgraphqlgen#68]
If the query below was passed by stdin, the Parser (v3.0.2) reacted with an error message like  ..."/graphql/June2018/#Document".

```
        query { 
           person(name: "Joe") { ...personFields } 
        }

        fragment personFields on Person { id  }
```

Note the blank line before the fragment definition. I found this while testing a  main loop more or less copied from the today example. Therein, the statement  
```

        while (std::getline(std::cin, line)) {input.append(line);}

```
effectively strips newline characters. 

When feeding the query via stdin, the query resulted in an error -- but not when the query was passed as a filename to be read via peg::parseFile(argv[1]) directly. Yet the real problem seems to be hidden in the parser. The follwing input (with angle brackets denoting the exact content )
```  
      <query{person(name:"Joe"){...personFields}}fragment personFields on Person {id}>
```
fails with boths variants (stdin, passing file name: premature EOF), whereas inserting a space between  "} and "fragment" is sufficient to get the input accepted. 

Since the grammar looks fine this behaviour may also be caused by a compiler bug. I used gcc-9.1. gcc-9.2 did not succeed because of some weired problems within a cppgraphqlgen header.

**Comment by wravery** [comment]
It's just a bug in the sample (not compiler related). Should be pretty easy to fix.

**Comment by soustelle** [comment]
Maybe you closed this bug a bit early? As I explained above, the real problem is not the test program, but the fact that the parser, for some reason, currently expects whitespace or linefeeds between the end of a preceding query definition and the start of a fragment definition, i.e. between "**}**" and "**fragment**" :
```
query{person(name:"Joe"){...personFields}}fragment personFields on Person {id}
``` 
I constructed this example in order to see if there is a general problem wrt whitespace characters -- which is obviously not so, except for the suprising condition mentioned above. 

The June 2018 document is unclear, even conflicting.  The gist of the paragraphs 2.1.2, 2.1.3 and also 2.1.5 is that whitespace, linefeeds and even commas are used 

>to improve legibility of source text and separate lexical tokens (2.1.5) 

Lexical tokens include names and punctuators (2.1.6). Curly braces are punctuators (2.1.8). Thus an official could argue that the current implementation correctly insists on at least one whitespace character in order to solve the otherwise intractable problem of separating a curly brace  from an identifier, a "name" token (2.1.9). If this would be so, then why there is no such problem between "query" and "person" ? 

Yet there is also a clarification regarding "Ignored Tokens" (2.1.7):

> Before and after every lexical token may be any amount of ignored tokens including WhiteSpace and Comment. No ignored regions of a source document are significant, [...]
 
"Any amount" of whithespace, commas and newlines includes zero occurences.

**Comment by wravery** [comment]
Ah, got it. There are really two bugs here then, I'd rather track then separately.

@soustelle, do you want to open a second issue (you should get credit for the GitHub activity if you want it), or shall I?

**Comment by wravery** [comment]
Found the bug, BTW. It's in the grammar definition for `graphql::peg::document_content`:

`list<definition, plus<ignored>>` should be `list<definition, star<ignored>>`

I want to review the options for `definition` to see if this could make any of them ambiguous, but if it did that should just result in a parsing failure.

**Comment by soustelle** [comment]
@**wravery** 
I'm more than happy that you found the cause (which I looked for myself, unsuccessfully). Just proceed and open a new report as it fits you.
